//LOCALHOST
### Get all contacts
GET http://localhost:3001/songs
 
### Get contacts by id
GET http://localhost:3001/songs/6643faff9112ce666479d40a


### Create Contact
POST http://localhost:3001/songs HTTP/1.1
content-type: application/json
  
{
    "band": "Example Band",
    "songs": [
        {"title": "a",
         "time": "3:27", 
         "album": "Wovoka",
         "length": 300, 
         "genre": "Rock"}
         ]
}


### Put contact
PUT http://localhost:3001/songs/6643faff9112ce666479d40b HTTP/1.1
content-type: application/json
 
{
    "band": "example",
    "songs": [
        {"title": "Me estoy enamorando",
         "time": "4:41", 
         "album": "Póntelo en le lengua",
         "length": "400", 
         "genre": "Rock"}
         ]
}
  

 
### DELETE contact
DELETE http://localhost:3001/songs/6646862dbb556031e05b1bfc


